//-----------------------------------------------------------------------------
//============= DO NOT EDIT THIS FILE =========================================
//-----------------------------------------------------------------------------
public class Student {
    private int id;
    private String name;
    private boolean fee;

    public Student() {
    }

    public Student(int id, String name, boolean fee) {
        this.id = id;
        this.name = name;
        this.fee = fee;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isFee() {
        return fee;
    }

    public void setFee(boolean fee) {
        this.fee = fee;
    }
    
    @Override
    public String toString(){
        return "("+id+","+name+","+fee+")";
    }  
}
//-----------------------------------------------------------------------------
//============= DO NOT EDIT THIS FILE =========================================
//-----------------------------------------------------------------------------
